
DROP TABLE IF EXISTS tool;
DROP TABLE IF EXISTS material;

CREATE TABLE IF NOT EXISTS tool(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(75)
);


CREATE TABLE IF NOT EXISTS material(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(75)
);

CREATE TABLE IF NOT EXISTS announcement(
  id INT AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(400),
  created_date DATE,
  expiration_date DATE
);






